project: 
  type: book
  output-dir: docs
  pre-render: content/functions.R
  # post-render: content/post-render.R

book: 
  page-navigation: true
  title: "GAP Production Data Documentation" 
  site-url: "https://afsc-gap-products.github.io/gap_products" 
  repo-url: "https://github.com/afsc-gap-products/gap_products"
  repo-actions: [edit, source, issue]
  favicon: img/favicon.png
  downloads: [pdf, docx]
  search: true
  author:
    - name: Bering Sea Survey Team
      email: afsc.gap.metadata@noaa.gov 
      note: https://github.com/afsc-gap-products
      affiliations:
        - name: NOAA Fisheres Alaska Fisheries Science Center
          department: Groundfish Assessment Program
    - name: Gulf of Alaska and Aleutian Island Survey Team
      email: afsc.gap.metadata@noaa.gov 
      note: https://github.com/afsc-gap-products
      affiliations:
        - name: NOAA Fisheres Alaska Fisheries Science Center
          department: Groundfish Assessment Program
  chapters:
    - part: index.qmd
      chapters:
        - content/intro-survey-background.qmd
        - content/intro-workflow.qmd
        - content/intro-news.qmd
    - part: content/product-intro.qmd
      chapters:
        - content/product-metadata.qmd
      #  - content/product-metadata-column.qmd
      #  - content/product-gapindex.qmd
    - part: content/akfin-intro.qmd
      chapters:
        - content/akfin-metadata.qmd
        - content/akfin-oracle-sql-r.qmd
        - content/akfin-api-r.qmd
    - part: content/foss-intro.qmd
      chapters:
        - content/foss-metadata.qmd
        - content/foss-platform.qmd
        - content/foss-api-r.qmd
        - content/foss-api-py.qmd
        - content/foss-oracle-r.qmd
    - part: content/other-intro.qmd
      chapters:
        - content/other-pkgs.qmd
        - content/other-reports.qmd
        - content/other-outreach.qmd
    - part: content/end-contact-us.qmd # content/end-acknowledgements.qmd # content/end.qmd
      chapters:
        - content/end-run-notes.qmd
        - content/end-data-constraints.qmd
        - content/end-acknowledgements.qmd
        - content/end-refs.qmd
        # - content/end-contact-us.qmd

  page-footer:
    right: "[U.S. Department of Commerce](https://www.commerce.gov/) | [National Oceanographic and Atmospheric Administration](https://www.noaa.gov) | [NOAA Fisheries](https://www.fisheries.noaa.gov/)" 
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#D9E3E4"
    logo: "https://avatars.githubusercontent.com/u/91760178?s=96&amp;v=4"
    favicon: img/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://github.com/afsc-gap-products
        text: "AFSC GAP Survey Data Products"
    style: "docked"
    search: true
    collapse-level: 1

bibliography: [content/references.bib]
csl: content/references.csl

execute:
  echo: false
  # eval: true
  error: false
  message: false
  comment: false
  warning: false
  code-overflow: wrap
  # freeze: auto

format:
  titlepage-pdf:
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    titlepage: "plain"
    keep-tex: true
    latex_engine: xelatex
    pandoc_args: "--latex-engine-opt=--enable-write18"
  docx:
    toc: true
    toc-depth: 2
    reference-doc: template.docx
    always_allow_html: true
  html:
    theme: [cosmo, assets/theme.scss] 
    toc: true
    toc-depth: 3
    number-sections: false
    include-before-body: translate.html    

filters:
  - assets/include-files.lua
  - quarto

# Comment next 2 lines if the PDF is having trouble
metadata-files:
  - _frontmatter.yml
  - quarto 
